stages:
  - build

variables:
  DOCKER_IMAGE: 'node:14'

before_script:
  - npm install -g pm2

install_dependencies:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - npm install  # Add your specific installation commands here

build:
  image: node
  script:
    - npm install
  tags:
    - docker





