enum user_role {
  patient
  dentist
  admin
}

table clinic {
  id int [pk]
  name varchar
  latitude double
  longitude double
}

table logs {
  id int [pk]
  timestamp timestamp
  topic varchar
  payload varchar
}

table user {
  id int [pk]
  name varchar
  username varchar
  pw_hash varchar
  clinic_id int
  role user_role
}

ref: user.clinic_id > clinic.id

table timeslot {
  id int [pk]
  dentist_id int
  start_time datetime
  end_time datetime
}
ref: timeslot.dentist_id > user.id

table patient_on_dentist {
  patient_id int
  dentist_id int
  favorite_dentist boolean
  rating int

  indexes {
    (patient_id, dentist_id) [pk]
  }
}
ref: patient_on_dentist.patient_id > user.id
ref: patient_on_dentist.dentist_id > user.id

enum notification_topic {
  confirmed
  cancelled
}
table notification {
  id int [pk]
  user_id int
  topic notification_topic
  message text
  read boolean 
}
ref: notification.user_id > user.id


table appointment {
  id int [pk]
  timeslot_id int
  patient_id int
  dentist_id int
  cancelled boolean [default: false]
  confirmed boolean [default: false]
}
ref: appointment.patient_id > user.id
ref: appointment.dentist_id > user.id
ref: appointment.timeslot_id > timeslot.id

